// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'http://192.168.10.33:8000',
  defaultLanguage: 'fr-FR',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
